---
title: "00Project Summary"
author: "Avery Bishop"
date: "2025-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Project Summary

  The main points that I have been working towards since the last update include gaining a complete understanding of the data using some preliminary summary metrics, as well as trying to decipher what different distinctions and niche details the data set includes so I can make the data conform to what I am using it for. I have cleaned some date formatting successfully in order to create usable date data to later match against my Lahman database for my total thesis project code. I then filtered out any instance of pitcher only and minor league injury data, making sure to note the many interesting ways the data labels the different positions as well as combined positions such as SP-RP, RP-SP, p-DH, p-OF, etc. I then double checked the 40man distinction because some of the listings for players labeled them as not a part of the 40 man roster however still a part of the major league team, and it is possible for one to not be a part of the 40 man but still on the big league team in occurrences of September call-ups, injury designations, etc. I then moved to trying to understand what is the point of the HINJ designation for injury, trying to figure out what that means to this data set. Outside research led me to believe it was some sort of phantom designation if there wasn't an IL or DL listing for the injury, I checked and there was a couple designations in the notes section even though they were listed as HINJ. Then I checked whether it was just the length part on the list that wasn't specified, yet Eric Young is listed as HINJ and in his notes it says DL-15. I am still unclear as to what the HINJ designation specifically means, as the baseball cube website doesn't define it anywhere on their glossary/key, and my plotting of the data tells me the majority of my data is designated as HINJ. 

  Moving into the plotting, I believed I needed an understanding of where my designations are spread, and the plot discerning how much of each designation I had led me to understand that I needed to look into what HINJ was and how it was presented in the data set. I still need clarification on what HINJ is so I can accurately apply this data to my thesis without overlooking any important things in the bulk of my data obviously. I then decided to put together a scatter plot of a missed_time variable, basically taking the date they were added to the injury list and the date they were taken off and seeing the spread over time of all injuries actual missed_time reported. This is where I flagged that for people who are still playing and are still currently on the injured list, their end date is reported as "9999-12-31". I then removed all players from the missed_time plot who are still on the injured list so that my plot looked semi-plausible, however I left those dates in the actual data, still unsure how I am going to incorporate those yet. Overall I still need to refine a lot of what I have with this data, but how I am going to be refining it for use comes when I get a clearer picture on the specific uses I will have when incorporating it into my thesis. I have a clear idea of where I am going to use it currently, but how it will be used and interpreted in my modeling is something I will be figuring out in the very near future so I feel confident I will have a clear answer soon. 